name: Test DAGs

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip check
    - name: Test with Pytest
      run: |
        pip install pytest
        cd airflow/__tests__ || exit
        pytest hello_world_test.py -v
